# Starting from the legacypipe-nersc docker container, customize our build.  Be sure to do
#   docker login
#   docker pull legacysurvey/legacypipe:nersc
# before building and pushing the container with
#   docker build . -t flagnarg/legacyhalos --file Dockerfile-legacyhalos
#   docker push flagnarg/legacyhalos:latest
# Finally, run this container with:
#   docker run -it flagnarg/legacyhalos:latest

FROM legacysurvey/legacypipe:nersc

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"

# Install MPI following https://docs.nersc.gov/programming/shifter/how-to-use
RUN mkdir /build/
RUN cd /build \
    && wget https://www.mpich.org/static/downloads/3.3/mpich-3.3.tar.gz \
    && tar xvzf mpich-3.3.tar.gz \
    && cd /build/mpich-3.3 \
    && ./configure \
    && make -j4 \
    && make install \
    && make clean

RUN cd /build \
    && wget https://www.imagemagick.org/download/ImageMagick-7.0.8-46.tar.gz \
    && tar xvzf ImageMagick-7.0.8-46.tar.gz \
    && cd /build/ImageMagick-7.0.8-46 \
    && ./configure \
    && make \
    && make install \
    && make clean

RUN /sbin/ldconfig

# pip-install some additional dependencies
RUN for x in \
    mpi4py \
    healpy \
    seaborn \
    ; do pip3 --no-cache-dir install $x; done \
    && rm -Rf /root/.cache/pip

# Add the development version of photutils.
RUN pip3 uninstall -y photutils \
    && cd /build \
    && git clone https://github.com/astropy/photutils.git \
    && cd photutils \
    && python3 setup.py install
RUN rm -rf /build

# # Clone legacyhalos
# RUN git clone http://github.com/moustakas/legacyhalos.git legacyhalos && echo 1
# ENV PYTHONPATH $PYTHONPATH:/src/legacyhalos/py
