# Starting from the legacypipe-nersc docker container, customize our build.  Be sure to do
#   docker login
#   docker pull legacysurvey/legacypipe:nersc
# before building and pushing the container with
#   docker build . -t flagnarg/legacyhalos --file Dockerfile-legacyhalos
#   docker push flagnarg/legacyhalos:latest
# Finally, run this container with:
#   docker run -it flagnarg/legacyhalos:latest

FROM legacysurvey/legacypipe:nersc

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"

# Install MPI following https://docs.nersc.gov/programming/shifter/how-to-use
RUN mkdir /build/
RUN cd /build \
    && wget https://www.mpich.org/static/downloads/3.3/mpich-3.3.tar.gz \
    && tar xvzf mpich-3.3.tar.gz \
    && cd /build/mpich-3.3 \
    && ./configure \
    && make -j4 \
    && make install \
    && make clean \
    && rm /build/mpich-3.3.tar.gz

RUN cd /build \
    && wget https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.1.tar.gz \
    && tar xvzf mpi4py-3.0.1.tar.gz
RUN cd /build/mpi4py-3.0.1 \
    && python setup.py build \
    && python setup.py install \
    && rm -rf /build/
RUN /sbin/ldconfig

# pip-install some additional dependencies
RUN for x in \
    healpy \
    seaborn \
    ; do pip3 install $x; done \
    && rm -Rf /root/.cache/pip

# Add the development version of photutils.
RUN pip3 uninstall -y photutils \
    && git clone https://github.com/astropy/photutils.git \
    && cd photutils \
    && python3 setup.py install

# Clone legacyhalos
# RUN git clone http://github.com/moustakas/legacyhalos.git legacyhalos && echo 1
# ENV PYTHONPATH /src/legacyhalos/py:$PYTHONPATH
