#!/usr/bin/env python

"""Generate the sample for the legacyhalos/profiles paper. 

build-profiles-sample --clobber

"""
import os, argparse
import numpy as np

import fitsio
from astropy.table import Table

import legacyhalos.io
import legacyhalos.misc

sampledir = legacyhalos.io.sample_dir()
paper1dir = os.path.join( legacyhalos.io.paper1_dir(), 'data' )
paper2dir = os.path.join( legacyhalos.io.paper2_dir(), 'data' )

def write_mstarcat(prefix, dr, rows):
    """Read and write out the mstar catalogs for a given prefix.

    """
    for sfhgrid in np.atleast_1d(1):
    #for sfhgrid in np.atleast_1d( (1, 2) ):
        for phot in ('lsphot-{}'.format(dr), 'sdssphot-dr14'):
            samplefile = os.path.join(paper1dir, 'paper1-{}-sfhgrid{:02d}-{}.fits'.format(prefix, sfhgrid, phot))
            outfile = os.path.join(paper2dir, 'paper2-{}-sfhgrid{:02d}-{}.fits'.format(prefix, sfhgrid, phot))

            mstar = fitsio.read(samplefile, rows=rows, ext=1)
            kcorr = fitsio.read(samplefile, rows=rows, ext=2)

            print('Writing {}'.format(outfile))
            fitsio.write(outfile, mstar, extname='ISEDFIT', clobber=True)
            fitsio.write(outfile, kcorr, extname='KCORR')

def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('--dr', type=str, default='dr8', help='Data release to analyze.')
    parser.add_argument('--zmax', type=float, default='0.4', help='Maximum redshift.')
    parser.add_argument('--minpcen', type=float, default='0.9', help='Minimum P(cen) to make it into the sample.')

    args = parser.parse_args()

    prefix = 'centrals'
    samplefile = os.path.join(paper1dir, 'paper1-{}-{}.fits'.format(prefix, args.dr))
    outfile = os.path.join(paper2dir, 'paper2-{}-{}.fits'.format(prefix, args.dr))

    allcen = fitsio.read(samplefile, ext=1)

    rows = np.where((allcen['P_CEN'][:, 0] > args.minpcen) *
                    (allcen['BCG_SPEC_Z'] != -1) * # require specz
                    #(allcen['LAMBDA_CHISQ'] > 10) *
                    #(allcen['Z_LAMBDA'] >= 0.1) *
                    (allcen['Z_LAMBDA'] >= 0.05) *
                    (allcen['Z_LAMBDA'] <= args.zmax))[0]
    cen = allcen[rows]

    # Temporary hack to write out a pilot sample of 1000 galaxies drawn
    # uniformly from halo mass.
    if True:
        npilot = 1000

        mhalo = np.log10(legacyhalos.misc.lambda2mhalo(cen['LAMBDA_CHISQ'], redshift=cen['Z_LAMBDA']))

        nbin = 20
        _xbin = np.linspace(mhalo.min(), mhalo.max(), nbin)
        idx  = np.digitize(mhalo, _xbin)

        prob = np.zeros_like(mhalo)
        for kk in range(nbin):
            ww = idx == kk
            if np.sum(ww) > 1:
                prob[ww] = 1 / np.sum(ww)
        prob /= np.sum(prob)

        rand = np.random.RandomState(seed=1)
        these = rand.choice(len(cen), npilot, p=prob, replace=False)
        srt = np.argsort(cen['MEM_MATCH_ID'][these])
        rows = rows[these[srt]]
        
        cen = cen[these[srt]]

    print('Writing {} / {} centrals to {}'.format(len(cen), len(allcen), outfile))
    fitsio.write(outfile, cen, clobber=True)

    # Also write out the stellar masses and K-corrections based on the Tractor
    # photometry, but just based on SFHGRID01.
    write_mstarcat(prefix, args.dr, rows)
    
if __name__ == '__main__':
    main()
